// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.DBModels;

public partial class Medical
{
    public int Id { get; set; }

    public int? Userid { get; set; }

    public DateTime? Datestart { get; set; }

    public DateTime? Dateend { get; set; }

    public DateTime? Datecreate { get; set; }

    public virtual User User { get; set; }
}