// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.DBModels;

public partial class Post
{
    public int Id { get; set; }

    public string Description { get; set; }

    public double? Salary { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}