// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.DBModels;

public partial class User
{
    public int Id { get; set; }

    public string Fio { get; set; }

    public int? Postid { get; set; }

    public DateTime? Datebirth { get; set; }

    public DateTime? Datestart { get; set; }

    public int? Telegramid { get; set; }

    public string Password { get; set; }

    public virtual ICollection<Dayoff> Dayoffs { get; set; } = new List<Dayoff>();

    public virtual ICollection<Holiday> Holidays { get; set; } = new List<Holiday>();

    public virtual ICollection<Medical> Medicals { get; set; } = new List<Medical>();

    public virtual Post Post { get; set; }

    public virtual ICollection<Recycling> Recyclings { get; set; } = new List<Recycling>();

    public virtual ICollection<TaskYt> TaskYts { get; set; } = new List<TaskYt>();
}