// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.Database.Database.Models;

public partial class Availableday
{
    public string Fio { get; set; }

    public double? Dates { get; set; }
}