// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.Database.Database.Models;

public partial class Dayoff
{
    public int Id { get; set; }

    public DateTime? Date { get; set; }

    public bool? Isapp { get; set; }

    public int? Userid { get; set; }

    public DateTime? Datecreate { get; set; }

    public virtual User User { get; set; }
}