// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.Database.Database.Models;

public partial class Holiday
{
    public int Id { get; set; }

    public DateTime? Datestart { get; set; }

    public DateTime? Dateend { get; set; }

    public bool? Isappadmin { get; set; }

    public bool? Isappdirect { get; set; }

    public int? Userid { get; set; }

    public DateTime? Datecreate { get; set; }

    public bool? Isdelete { get; set; }

    public virtual User User { get; set; }
}