// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Realization.Database.Database.Models;

public partial class officeContext : DbContext
{
    public officeContext()
    {
    }

    public officeContext(DbContextOptions<officeContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Availableday> Availabledays { get; set; }

    public virtual DbSet<Dayoff> Dayoffs { get; set; }

    public virtual DbSet<Holiday> Holidays { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseNpgsql("Host=localhost;Database=office;Username=postgres;Password=123;Persist Security Info=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Availableday>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("availabledays");

            entity.Property(e => e.Dates).HasColumnName("dates");
            entity.Property(e => e.Fio)
                .HasMaxLength(255)
                .HasColumnName("fio");
        });

        modelBuilder.Entity<Dayoff>(entity =>
        {
            entity
                .HasNoKey()
                .ToTable("dayoff");

            entity.Property(e => e.Date)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("date");
            entity.Property(e => e.Datecreate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("datecreate");
            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnName("id");
            entity.Property(e => e.Isapp).HasColumnName("isapp");
            entity.Property(e => e.Userid).HasColumnName("userid");

            entity.HasOne(d => d.User).WithMany()
                .HasForeignKey(d => d.Userid)
                .HasConstraintName("fk_holiday_user");
        });

        modelBuilder.Entity<Holiday>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("holiday_pk");

            entity.ToTable("holiday");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Datecreate)
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasColumnType("timestamp without time zone")
                .HasColumnName("datecreate");
            entity.Property(e => e.Dateend)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("dateend");
            entity.Property(e => e.Datestart)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("datestart");
            entity.Property(e => e.Isappadmin).HasColumnName("isappadmin");
            entity.Property(e => e.Isappdirect).HasColumnName("isappdirect");
            entity.Property(e => e.Isdelete).HasColumnName("isdelete");
            entity.Property(e => e.Userid).HasColumnName("userid");

            entity.HasOne(d => d.User).WithMany(p => p.Holidays)
                .HasForeignKey(d => d.Userid)
                .HasConstraintName("fk_holiday_user");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("role_pk");

            entity.ToTable("role");

            entity.HasIndex(e => e.Id, "role_unique").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Login)
                .HasMaxLength(50)
                .HasColumnName("login");
            entity.Property(e => e.Name)
                .HasMaxLength(50)
                .HasColumnName("name");
            entity.Property(e => e.Password)
                .HasMaxLength(50)
                .HasColumnName("password");
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("users_pk");

            entity.ToTable("users");

            entity.HasIndex(e => e.Id, "users_unique").IsUnique();

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Datebirth)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("datebirth");
            entity.Property(e => e.Datestart)
                .HasColumnType("timestamp without time zone")
                .HasColumnName("datestart");
            entity.Property(e => e.Fio)
                .HasMaxLength(255)
                .HasColumnName("fio");
            entity.Property(e => e.Isdelete).HasColumnName("isdelete");
            entity.Property(e => e.Roleid).HasColumnName("roleid");
            entity.Property(e => e.Telegramid).HasColumnName("telegramid");

            entity.HasOne(d => d.Role).WithMany(p => p.Users)
                .HasForeignKey(d => d.Roleid)
                .HasConstraintName("fk_users_role");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}