// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.Database.Database.Models;

public partial class Role
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}