// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Realization.Database.Database.Models;

public partial class User
{
    public int Id { get; set; }

    public string Fio { get; set; }

    public DateTime? Datebirth { get; set; }

    public DateTime? Datestart { get; set; }

    public int? Telegramid { get; set; }

    public int? Roleid { get; set; }

    public bool? Isdelete { get; set; }

    public virtual ICollection<Holiday> Holidays { get; set; } = new List<Holiday>();

    public virtual Role Role { get; set; }
}